name: pinball_flame
description: Set of out-of-the-way solutions for common Pinball game problems.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  bloc: ^8.0.0
  flame: ^1.18.0
  flame_bloc: ^1.12.0
  flame_forge2d: ^0.18.1
  flutter:
    sdk: flutter
  geometry:
    path: ../geometry

dev_dependencies:
  flame_test: ^1.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
