name: geometry
description: Provides a set of helpers for working with 2D geometry.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies: 
  vector_math: ^2.1.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^6.0.0
