name: pinball_theme
description: Package containing themes for pinball game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/images/android/
    - assets/images/dash/
    - assets/images/dino/
    - assets/images/sparky/

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80
  integrations:
    flutter_svg: true
