name: pinball_components
description: Package with the UI game components for the Pinball Game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flame: ^1.1.1
  flame_forge2d:
    git:
      url: https://github.com/flame-engine/flame/
      path: packages/flame_forge2d/
      ref: a50d4a1e7d9eaf66726ed1bb9894c9d495547d8f
  flutter:
    sdk: flutter
  geometry:
    path: ../geometry
  intl: ^0.17.0
  pinball_flame:
    path: ../pinball_flame
  pinball_theme:
    path: ../pinball_theme

dev_dependencies:
  bloc_test: ^9.0.3
  flame_test: ^1.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  fonts:
    - family: PixeloidSans
      fonts:
        - asset: fonts/PixeloidSans-nR3g1.ttf
        - asset: fonts/PixeloidSansBold-RpeJo.ttf
          weight: 700
    - family: PixeloidMono
      fonts:
        - asset: fonts/PixeloidMono-1G8ae.ttf

  assets:
    - assets/images/
    - assets/images/ball/
    - assets/images/baseboard/
    - assets/images/boundary/
    - assets/images/dino/
    - assets/images/dino/animatronic/
    - assets/images/flipper/
    - assets/images/launch_ramp/
    - assets/images/dash/
    - assets/images/dash/bumper/a/
    - assets/images/dash/bumper/b/
    - assets/images/dash/bumper/main/
    - assets/images/android/spaceship/
    - assets/images/android/rail/
    - assets/images/android/ramp/
    - assets/images/android/ramp/arrow/
    - assets/images/android/bumper/a/
    - assets/images/android/bumper/b/
    - assets/images/android/bumper/cow/
    - assets/images/kicker/left/
    - assets/images/kicker/right/
    - assets/images/plunger/
    - assets/images/slingshot/
    - assets/images/sparky/
    - assets/images/sparky/computer/
    - assets/images/sparky/bumper/a/
    - assets/images/sparky/bumper/b/
    - assets/images/sparky/bumper/c/
    - assets/images/backboard/
    - assets/images/google_word/letter1/
    - assets/images/google_word/letter2/
    - assets/images/google_word/letter3/
    - assets/images/google_word/letter4/
    - assets/images/google_word/letter5/
    - assets/images/google_word/letter6/
    - assets/images/signpost/
    - assets/images/multiplier/x2/
    - assets/images/multiplier/x3/
    - assets/images/multiplier/x4/
    - assets/images/multiplier/x5/
    - assets/images/multiplier/x6/
    - assets/images/score/

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true
